import sys
import os
sys.path.insert(0, '.')
import swap

subnames = [x.split("-")[0] for x in os.listdir("config/")]
for subname in subnames:
	sub_config, reddit, sub = swap.create_reddit_and_sub(subname)
	message_content = "Hi Mod Team! I come to you today with yet another Swap Bot update.\n\nAs mentioned in my last message, I've added a feature that allows the Swap Bot to confirm transactions done on threads authored by Automoderator. This is particularly useful for subs that have monthly WTB threads.\n\nIn addition to all of the normal checks made on confirmations to ensure the integrity of the system, the bot makes the following checks specifically for confirmations on posts authored by Automoderator:\n\n* The bot will enforce that confirmation attempts are NOT top-level comments. This will both prevent the post from being spammed by confirmations and ensuring that the confirmation is linked to an actual attempt to Buy, Sell, or Trade, much like how the bot currently requires that confirmations are done in the post where the transaction originated. [Example](https://imgur.com/a/Bt0oNRD)\n\n* The bot will ensure that either the person tagging the bot or the person being tagged are the OP of the top most level comment in the comment there where the bot was invoked. This is similar in how the bot checks that either the person tagging the bot or the person being tagged are the OP of the post in confirmations done under normal circumstances. [Example](https://imgur.com/a/8xRZSSt)\n\n* If your sub has a post age threshold, the bot will treat the top most level comment as the initiating post and apply the age threshold in the same way. [Example](https://imgur.com/a/7emDm2b)\n\n* It will also deduplicate transactions based on the top most level comment, rather than deduplicating on a post basis. This is done because automod-authored threads can last for a long time, so it's very possible that a user will do a transaction with the same user twice and there be a sufficiently large amount of time in between transactions. [Example](https://imgur.com/a/HoWYsC5)\n\nAs of now, this feature is rolled out to all users. If your subreddit does not have posts authored by Automoderator, then you can ignore this as it will never apply to your sub. \n\nIf this update DOES apply to you, please communicate this change to your community members. Previously, users had to confirm transactions from automod-authored posts in one of their most recent posts. This change will allow them to do it right in the original thread instead. \n\nIf this update does apply to you but you have a reason for not wanting it, please let me know ASAP and I'll look into adding some logic that prevents confirmations done in automod-authored posts on your sub. \n\nThanks for taking the time to read this! Please let me know if you have any questions at all.\n\nBest,\n\nu/RegExr"
	sub.message("New Swap Bot Feature - Confirmations in Automod-Authored Posts", message_content)
