import praw
import sys
import os
sys.path.insert(0, '.')
import config


subnames = [x.split("-")[0] for x in os.listdir("config/")]
for subname in subnames:
	sub_config = config.Config(subname)
	reddit = praw.Reddit(client_id=sub_config.client_id, client_secret=sub_config.client_secret, user_agent='UserAgent', username=sub_config.bot_username, password=sub_config.bot_password)
	sub = reddit.subreddit(sub_config.subreddit_name)
	message_content = "Hello Mod Team!\n\nI come to you today with a new feature for the swap bot. This new feature is called **Flair Sharing**. Essentially, it allows any subreddit to share flair with another subreddit. Let's say, for example, that there are two subreddits: r/red and r/blue. There is substantial overlap in the user-base of both subs and the items being sold/traded on both subs are very similar. As such, a transaction on one sub is worth about the same as a transaction on another sub. Given this, the mods of either sub can elect to have the confirmations from the opposing sub also count as transactions for their sub. So, for example, the mods of r/Red and have transactions completed on r/Blue count for user flair in r/Red. And, if the mods of r/Blue want transactions from r/Red to count for their sub, they can do so as well.\n\nThis does **not** force any one sub to use flair from another sub. If the mods of r/Blue want nothing to do with r/Red, they can keep things as they are. They don't have to use flair from r/Red, even if the mods of r/Red want flair from r/Blue.\n\nAdditionally, this process is easily reversible. The individual confirmations stored in the database are still stored on a per-sub basis, so if r/Red ever decides they no longer want flair from r/Blue, they can elect to remove it and their users' flair will go back to only counting transactions from r/Red.\n\nThis feature is not for everyone, but it brings us one step closer to a more unified reddit Buy/Sell/Trade experience. Currently, there are 26 subreddits using the same bot system. These subreddits are as follows:\n\n* r/digitalcodesell\n* r/disneypinswap\n* r/ecigclassifieds\n* r/funkoswap\n* r/mousemarket\n* r/pkmntcgtrades\n* r/snackexchange\n* r/steelbookswap\n* r/uvtrade\n* r/vinylcollectors\n* r/bluraysale\n* r/disneystorekeyswap\n* r/ygomarketplace\n* r/comicswap\n* r/avexchange\n* r/watchexchange\n* r/coffee_exchange\n* r/discexchange\n* r/airsoftmarket\n* r/knife_swap\n* r/boardgameexchange\n* r/screenpass\n* r/figpinswap\n* r/fishingswap\n* r/digimoncardgame2021\n* r/thinkpadsforsale\n\nIf you would like your sub to count transactions completed on any of the above subs, please let me know! I will change your sub's configuration to include flair from those subs as well.\n\nIf you do decide to share flair with another sub, be sure to let the users of your sub know! And maybe make reference to it somewhere in the sidebar of your sub. That way, it's clear to your users why their score might be higher than they expected.\n\nThanks again for your continued partnership! Hopefully this feature unlocks new potential for the Buy/Sell/Trade communities of reddit.\n\nBest,\n\nu/RegExr"
	sub.message("New Swap Bot Feature - Flair Sharing", message_content)
